/*
* Copyright (c) 2025, NVIDIA CORPORATION. All rights reserved.
*
* Permission is hereby granted, free of charge, to any person obtaining a
* copy of this software and associated documentation files (the "Software"),
* to deal in the Software without restriction, including without limitation
* the rights to use, copy, modify, merge, publish, distribute, sublicense,
* and/or sell copies of the Software, and to permit persons to whom the
* Software is furnished to do so, subject to the following conditions:
*
* The above copyright notice and this permission notice shall be included in
* all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
* THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*/

#pragma once

#include "rtx_render/graph/rtx_graph_component_macros.h"

namespace dxvk {
namespace components {

// Test component with Any flexible type (for testing type resolution)
#define LIST_INPUTS_FLEXANY(X) \
  X(RtComponentPropertyType::Any, 0, inputA, "Input A", "First flexible any input") \
  X(RtComponentPropertyType::Any, 0, inputB, "Input B", "Second flexible any input")

#define LIST_STATES_FLEXANY(X)

#define LIST_OUTPUTS_FLEXANY(X) \
  X(RtComponentPropertyType::Bool, false, output, "Output", "Equality result")

template <RtComponentPropertyType inputAPropertyType, RtComponentPropertyType inputBPropertyType>
class TestFlexAny : public RtRegisteredComponentBatch<TestFlexAny<inputAPropertyType, inputBPropertyType>> {
private:
  static constexpr RtComponentPropertyType outputPropertyType = RtComponentPropertyType::Bool;
  
  REMIX_COMPONENT_BODY(
    /* the Component class name */ TestFlexAny,
    /* the UI name */        "Test Flex Any",
    /* the UI categories */  "test",
    /* the doc string */     "Test component for Any flexible type resolution",
    /* the version number */ 1,
    LIST_INPUTS_FLEXANY, LIST_STATES_FLEXANY, LIST_OUTPUTS_FLEXANY
  )
  
  void updateRange(const Rc<DxvkContext>& context, const size_t start, const size_t end) {
    for (size_t i = start; i < end; i++) {
      m_output[i] = (m_inputA[i] == m_inputB[i]);
    }
  }
};

#undef LIST_INPUTS_FLEXANY
#undef LIST_STATES_FLEXANY
#undef LIST_OUTPUTS_FLEXANY

// Test component with NumberOrVector flexible type (for testing type resolution)
#define LIST_INPUTS_FLEXNUMBEROV(X) \
  X(RtComponentPropertyType::NumberOrVector, 0, inputA, "Input A", "First flexible number or vector input") \
  X(RtComponentPropertyType::NumberOrVector, 0, inputB, "Input B", "Second flexible number or vector input")

#define LIST_STATES_FLEXNUMBEROV(X)

#define LIST_OUTPUTS_FLEXNUMBEROV(X) \
  X(RtComponentPropertyType::NumberOrVector, 0, output, "Output", "Sum of inputs")

template <RtComponentPropertyType inputAPropertyType, RtComponentPropertyType inputBPropertyType, RtComponentPropertyType outputPropertyType>
class TestFlexNumberOrVector : public RtRegisteredComponentBatch<TestFlexNumberOrVector<inputAPropertyType, inputBPropertyType, outputPropertyType>> {
  REMIX_COMPONENT_BODY(
    /* the Component class name */ TestFlexNumberOrVector,
    /* the UI name */        "Test Flex NumberOrVector",
    /* the UI categories */  "test",
    /* the doc string */     "Test component for NumberOrVector flexible type resolution",
    /* the version number */ 1,
    LIST_INPUTS_FLEXNUMBEROV, LIST_STATES_FLEXNUMBEROV, LIST_OUTPUTS_FLEXNUMBEROV
  )
  
  void updateRange(const Rc<DxvkContext>& context, const size_t start, const size_t end) {
    for (size_t i = start; i < end; i++) {
      // We want to allow all reasonable number + number type combinations, i.e. `int32 + uint64`.  
      // To compile those combinations, we need to disable the `narrowing conversion` warning.
      #pragma warning(push)
      #pragma warning(disable: 4244)
      m_output[i] = m_inputA[i] + m_inputB[i];
      #pragma warning(pop)
    }
  }
};

#undef LIST_INPUTS_FLEXNUMBEROV
#undef LIST_STATES_FLEXNUMBEROV
#undef LIST_OUTPUTS_FLEXNUMBEROV

// Forward declarations for type variant creation functions (generated by macros in .cpp file)
void createTypeVariantsForTestFlexAny();
void createTypeVariantsForTestFlexNumberOrVector();

}  // namespace components
}  // namespace dxvk

